### ISSUE TITLE
Error: "any command from /node_modules" command not found

### ISSUE THREAD

**Issue by sadamia** [tomwray13/nest-docker-postgres-prisma#5]
Hi Tom,

The docker-compose file fails on stage `development` it can't execute any scripts from `node_modules`.
In this case, it won't be able to run `npm run start:dev` and will end up with this error `sh: 1: nest: not found`.
Assuming the `node_modules` are not present on the host machine.

I relate to these files [Docker-dompose.yml](https://github.com/tomwray13/nest-docker-postgres-prisma/blob/main/docker-compose.yml) and [Dockerfile](https://github.com/tomwray13/nest-docker-postgres-prisma/blob/main/Dockerfile)

The solution which I found is this 
docker-compose.yml
```
  api:
    user: "root:node"
    build:
      dockerfile: Dockerfile
      context: .
      # Only will build development stage from our dockerfile
      target: development
    env_file:
        - .env
    volumes:
      - ./src:/user/src/app/src
    # Run in dev Mode: npm run start:dev
    command: npm run start:dev
    ports:
      - 3000:3000
    depends_on:
```

I changed the volume path and also added the user mapping.
Do you have a better suggestion @tomwray13  ?

OS
ProductName:		macOS
ProductVersion:		13.4.1
BuildVersion:		22F82
